### ISSUE TITLE
package:printing doesn't work with package:web v1.1.0

### ISSUE THREAD

**Issue by xvrh** [DavBfr/dart_pdf#1747]
package:printing doesn't work with the latest version of package:web (1.1.0)

There is a compilation error when compiling for the Web

```dart
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../../../../.pub-cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:132:19:
Error: The operator '[]=' isn't defined for the class 'Window'.
        web.window['module'] = module;
                  ^
../../../../../.pub-cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:135:19:
Error: The operator '[]=' isn't defined for the class 'Window'.
        web.window['exports'] = exports;
                  ^
Error: Compilation failed.
```

**To Reproduce**
Compile a Flutter app for the web plaform with both package:printing and package:web: 1.1.0

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [ ] Windows
 - [ ] Linux

**Comment by HiramaniPatel** [comment]
I have also get same error on complilation 

Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../.pub-cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:132:19:
Error: The operator '[]=' isn't defined for the class 'Window'.
        web.window['module'] = module;
                  ^
../../.pub-cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:135:19:
Error: The operator '[]=' isn't defined for the class 'Window'.
        web.window['exports'] = exports;
                  ^

**Comment by wechulimaven** [comment]
I`m also experiencing the same issue . Any help
`../../../.pub-cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:132:19: Error: The operator '[]=' isn't defined for the class 'Window'.
Try correcting the operator to an existing operator, or defining a '[]=' operator.
        web.window['module'] = module;
                  ^`

**Comment by ifuterman** [comment]
For me the same

**Comment by AlexFeldmeier** [comment]
Changing the cached version will have issues if you do CI/CD or have multiple machines on the same project. Another temporary fix is to lock `web` to `1.0.0`

```
dependencies:
  web: 1.0.0
```

**Comment by ifuterman** [comment]
> Changing the cached version will have issues if you do CI/CD or have multiple machines on the same project. Another temporary fix is to lock `web` to `1.0.0`
> 
> ```
> dependencies:
>   web: 1.0.0
> ```

More correct way:
```
dependency_overrides:
   web: 1.0.0
```

**Comment by Ammutadori83** [comment]
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:132:19: Error: The operator '[]=' isn't defined for the class 'Window'.
Try correcting the operator to an existing operator, or defining a '[]=' operator.
        web.window['module'] = module;
                  ^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/printing-5.13.2/lib/printing_web.dart:135:19: Error: The operator '[]=' isn't defined for the class 'Window'.
Try correcting the operator to an existing operator, or defining a '[]=' operator.
        web.window['exports'] = exports;
                  ^
Failed to compile application.

same for me

**Comment by DavBfr** [comment]
The master branch is compatible, I'll publish a new version soon.
